### ISSUE TITLE
cgi files

### ISSUE THREAD

**Issue by tomas-vacek** [hilch/systemdump.py#1]
Dear Christoph,
you are using special addresses with a lot of parameters in the requests (cgiFileLoop.cgi, svg.cgi). 
Where can I find the documentation for those addresses and their parameters? Is there any list of those cgi addresses? 

thanks
Tomas

**Comment by hilch** [comment]
Hi Tomas,
unfortunately there is no documentation anywhere. You 'll have to find out with the browser's dev tools which cgi is used for what and what parameters have to be used with them.
Best Regards, Christoph

**Comment by tomas-vacek** [comment]
Hi Christoph,
could you give me a hint how to do it? I would like to download diagnostic logbooks from CPU and convert to xml file (from computer with no Automation Studio). 
I saw you made a logbook viewer. So, do you know format of BR logbook binary file (e.g. System.br, User.br)? 
Best Regards
Tomas

**Comment by hilch** [comment]
> could you give me a hint how to do it?

well you'll need some basics about web programming then.
open SDM page and manually create the dump
open browser's dev tools (CTRL+SHIFT+i) and select tab 'network'.
pick the web request of your button action and copy it:

![devtools](https://user-images.githubusercontent.com/11504129/219019417-442225c2-5e70-4c65-b04c-78b01649c846.png)

> I saw you made a logbook viewer.

I just made a  simple logbook viewer with PVI but PVI hides the inner structure of the logs. There is no documentation about the inner structure of the logs.

**Comment by hilch** [comment]
Hi @tomas-vacek 

> I saw you made a logbook viewer. So, do you know format of BR logbook binary file (e.g. System.br, User.br)?

did you see GUID ce85f6fe-797a-45a4-9353-cddac9db5fc9 'PviTransUtil.dll' ?

**Comment by tomas-vacek** [comment]
thanks for this tip

**Comment by hilch** [comment]
Hi @tomas-vacek

> I saw you made a logbook viewer. So, do you know format of BR logbook binary file (e.g. System.br, User.br)?

I still have no official description of the *.br but I did some reverse engineering 

https://github.com/hilch/Pvi.py/blob/main/examples/logger2.py
